---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[site-otrs-sectypo3org::default]
    attributes:
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8086}]
      - ["private_network", {ip: "192.168.33.35"}]
