---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.10

suites:
  - name: default
    run_list:
      - recipe[site-securityteamtypo3org::default]
    attributes:
      mysql:
        server_root_password: root
      otrs:
        fqdn: otrs.vagrant
        version: 5.0.14
      site-securityteamtypo3org:
         ssl_certificate: wildcard.vagrant
    driver_config:
      network:
      - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
      - ["private_network", {ip: "192.168.34.35"}]
